stages:
  - test
  - build

eslint:
  stage: test
  image: node:latest
  before_script:
   - npm install
  script:
    - npm run eslint

stylelint:
  stage: test
  image: node:latest
  before_script:
   - npm install
  script:
    - npm run stylelint

build_master:
  stage: build
  image: node:latest
  before_script:
    - npm install
  script:
    - npm run build
  only:
    - master

# On branches except master: verify that build works
build:
  stage: build
  image: node:latest
  before_script:
    - npm install
  script:
    - npm run build
  except:
    - master
